#!/usr/bin/env ruby

require 'rubygems'
require 'redis'
require 'yaml'

redis_contructor_info = {}
configFilePath = File.join(File::SEPARATOR,"etc","munin","plugin-conf.d","redis.conf")

if (File.exists?(configFilePath))
  redis_constructor_info = YAML.load(File.open(configFilePath))
else
  connection_info = YAML.load(File.open("/etc/munin/plugin-conf.d/redis_connection.yml"))
  redis_constructor_info = { :host => connection_info["host"], :port => connection_info["port"], :password => connection_info["password"] }
end

config = ARGV.any? { |a| a =~ /config/ }

if config
  puts "graph_title Redis Connections rate"
  puts "graph_category redis"
  puts "graph_vlabel connections/s"
  puts "graph_info This graph monitors the connctions rate"

  puts "connections.label connections"
  puts "connections.type COUNTER"
  puts "connections.min 0"
else
  redis = Redis.new(redis_constructor_info)
  info  = redis.info

  puts "connections.value" + " " + info['total_connections_received'].to_s
end