#!/usr/bin/env ruby

require 'rubygems'
require 'redis'
require 'yaml'

redis_contructor_info = {}

configFilePath = File.join(File::SEPARATOR,"etc","munin","plugin-conf.d","redis.conf")
if (File.exists?(configFilePath))
  redis_constructor_info = YAML.load(File.open(configFilePath))
else
  connection_info = YAML.load(File.open("/etc/munin/plugin-conf.d/redis_connection.yml"))
  redis_constructor_info = { :host => connection_info["host"], :port => connection_info["port"], :password => connection_info["password"] }
end

config = ARGV.any? { |a| a =~ /config/ }

if config
  puts "graph_title Redis Memory"
  puts "graph_category redis"
  puts "graph_vlabel mem used"
  puts "graph_info This graph monitors the commands rate"
  puts "graph_args --base 1024 -l 0"

  puts "memory.label memory"
  puts "memory.info Amount of mem used by redis"
  puts "memory.type GAUGE"
  puts "memory.min 0"
  puts "memory.draw AREA"

else
  redis = Redis.new(redis_constructor_info)
  info  = redis.info

  puts "memory.value" + " " + info['used_memory'].to_s
end