#!/usr/bin/env ruby

require 'rubygems'
require 'redis'
require 'yaml'

redis_contructor_info = {}

configFilePath = File.join(File::SEPARATOR,"etc","munin","plugin-conf.d","redis.conf")
puts configFilePath
if (File.exists?(configFilePath))
  redis_constructor_info = YAML.load(File.open(configFilePath))
else
  connection_info = YAML.load(File.open("/etc/munin/plugin-conf.d/redis_connection.yml"))
  redis_constructor_info = { :host => connection_info["host"], :port => connection_info["port"], :password => connection_info["password"] }
end

config = ARGV.any? { |a| a =~ /config/ }

if config
  puts "graph_order commands hits misses"

  puts "graph_title Redis Commands rate"
  puts "graph_category redis"
  puts "graph_vlabel commands/s"
  puts "graph_info This graph monitors the commands rate"

  puts "commands.label commands/s"
  puts "commands.type COUNTER"
  puts "commands.min 0"

  puts "hits.label cache hits"
  puts "hits.type COUNTER"
  puts "hits.min 0"

  puts "misses.label cache misses"
  puts "misses.type COUNTER"
  puts "misses.min 0"
else
  redis = Redis.new(redis_constructor_info)
  info  = redis.info

  puts "commands.value" + " " + info['total_commands_processed'].to_s
  puts "hits.value #{info['keyspace_hits']}"
  puts "misses.value #{info['keyspace_misses']}"
end